# environment.yml
name: cognitivesky
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - pip
  - pip:
      - transformers
      - sentence-transformers
      - umap-learn
      - scikit-learn
      - emoji
      - torch
      - python-louvain
      - supabase
      - libsql-experimental
      - python-dotenv
